name: barg_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  base_platform:
    path: packages/base_platform
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.2
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  json_annotation: ^4.4.0
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.3
  lint: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
